# Generated by Django 3.1.7 on 2021-02-21 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(default='Created', max_length=60)),
                ('result', models.CharField(default='Processing', max_length=60)),
                ('note', models.CharField(max_length=250)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.command')),
            ],
        ),
    ]
