# Generated by Django 3.1.6 on 2021-03-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_commandexecution_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandexecution',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
