# Generated by Django 3.1.6 on 2021-03-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210331_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandexecution',
            name='note',
            field=models.CharField(max_length=1000),
        ),
    ]
