# Generated by Django 3.1.7 on 2021-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210331_2224'),
    ]

    operations = [
    ]
