# Generated by Django 3.1.7 on 2021-04-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210407_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandexecution',
            name='timestamp',
        ),
    ]
