# Generated by Django 3.1.7 on 2021-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_commandexecution_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandexecution',
            name='timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
