# Generated by Django 3.1.6 on 2021-04-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_module_module_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module_value',
            new_name='ModuleValue',
        ),
    ]
