# Generated by Django 3.1.6 on 2021-04-28 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210428_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
