# Generated by Django 3.1.6 on 2021-04-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_modulevalue_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulevalue',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
